#!/bin/bash

# YunoHost-Helfer laden
source /usr/share/yunohost/helpers

# Eingaben abrufen
ftp_server=$YNH_APP_ARG_FTP_SERVER
ftp_user=$YNH_APP_ARG_FTP_USER
ftp_password=$YNH_APP_ARG_FTP_PASSWORD
ftp_path=$YNH_APP_ARG_FTP_PATH

# Cron-Job einrichten
crontab -l | { cat; echo "0 2 * * * yunohost backup create --output-dir /home/yunohost.backup/archives && ftp -inv $ftp_server << EOF
user $ftp_user $ftp_password
cd $ftp_path
mput /home/yunohost.backup/archives/*
quit
EOF"; } | crontab -
