packaging_format = 2

id = "ftp_upload_ynh"
name = "FTP Upload"
description.de = "Eine App, die Backups erstellt und auf einen FTP-Server hochlädt."
description.en = "An app that creates backups and uploads them to an FTP server."

version = "1.0~ynh1"

yunohost_version = ">= 11.2.9"

[maintainers]
name = "Eugen Fritzler"
email = "eugen@fritzler-host.de"

[upstream]
license = "GPL-3.0"
code = "https://github.com/Fr3ak88/ftp_upload_ynh"

[integration]
yunohost = ">= 11.2.9"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "128M"
ram.runtime = "64M"

[install]
[install.ftp_server]
ask.en = "Enter the FTP server address:"
ask.de = "Geben Sie die Adresse des FTP-Servers ein:"
type = "string"
help.en = "Example: ftp.example.com"
help.de = "Beispiel: ftp.example.com"

[install.ftp_user]
ask.en = "Enter the FTP username:"
ask.de = "Geben Sie den FTP-Benutzernamen ein:"
type = "string"

[install.ftp_password]
ask.en = "Enter the FTP password:"
ask.de = "Geben Sie das FTP-Passwort ein:"
type = "password"

[install.ftp_path]
ask.en = "Enter the FTP path for backups:"
ask.de = "Geben Sie den FTP-Pfad für Backups ein:"
type = "string"
help.en = "Example: /backups/"
help.de = "Beispiel: /backups/"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["backups"]

    [resources.permissions]

    [resources.apt]
    packages = [
        "ftp",
    ]
