#!/bin/bash

# YunoHost-Helfer laden
source /usr/share/yunohost/helpers

# Hier können Sie zusätzliche Schritte hinzufügen, die während des Upgrades ausgeführt werden sollen
# Zum Beispiel:
echo "Upgrade-Prozess gestartet."

# Aktualisieren Sie hier alle notwendigen Konfigurationen oder Dateien
# Zum Beispiel:
# cp /path/to/new/config /path/to/old/config

echo "Upgrade erfolgreich abgeschlossen."

