#!/bin/bash
source /usr/share/yunohost/helpers

# Argumente abrufen und validieren
ftp_server="$YNH_APP_ARG_FTP_SERVER"
ftp_user="$YNH_APP_ARG_FTP_USER"
ftp_password="$YNH_APP_ARG_FTP_PASSWORD"
ftp_path="$YNH_APP_ARG_FTP_PATH"

# Debug-Ausgaben hinzufügen
ynh_print_info --message="DEBUG: FTP Server = $ftp_server"
ynh_print_info --message="DEBUG: FTP User = $ftp_user"
ynh_print_info --message="DEBUG: FTP Password = $ftp_password"
ynh_print_info --message="DEBUG: FTP Path = $ftp_path"

if [ -z "$ftp_server" ] || [ -z "$ftp_user" ] || [ -z "$ftp_password" ] || [ -z "$ftp_path" ]; then
  ynh_die --message="FTP-Daten fehlen."
fi

# FTP-Daten persistent speichern
ynh_app_setting_set --app="$app" --key=ftp_server --value="$ftp_server"
ynh_app_setting_set --app="$app" --key=ftp_user --value="$ftp_user"
ynh_app_setting_set --app="$app" --key=ftp_password --value="$ftp_password"
ynh_app_setting_set --app="$app" --key=ftp_path --value="$ftp_path"

# Pakete installieren
ynh_package_update
ynh_package_install ftp

# Cronjob-Template mit Variablen ersetzen
ynh_add_config --template="../conf/cron_job" \
               --destination="/etc/cron.d/$app" \
               replace_vars="FTP_SERVER,FTP_USER,FTP_PASSWORD,FTP_PATH"

ynh_print_info --message="App erfolgreich installiert."
