#!/bin/bash

# YunoHost-Helfer laden
source /usr/share/yunohost/helpers

# Hier können Sie zusätzliche Schritte hinzufügen, die während der Wiederherstellung ausgeführt werden sollen
# Zum Beispiel:
echo "Wiederherstellungsprozess gestartet."
